### ISSUE TITLE
Error when creating graphics for variant `chr3:10088407AG>A`

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/vmvt#59]
When creating donor graphics for the variant `chr3:10088407AG>A`

```java
@Test
public void someTest() {
    final String svg = vmvtGenerator.getDonorDistributionSvg("TTAgtaagt", "TTAtaagtg");
    System.out.println(svg);
}
```

the following error is thrown:
```java
org.monarchinitiative.vmvt.core.except.VmvtRuntimeException: Bad data -- measured delta greater than max

  at org.monarchinitiative.vmvt.core.svg.delta.DeltaSvg.writeTicks(DeltaSvg.java:188)
  at org.monarchinitiative.vmvt.core.svg.delta.DeltaSvg.write(DeltaSvg.java:267)
  at org.monarchinitiative.vmvt.core.svg.delta.DeltaSvg.getSvg(DeltaSvg.java:238)
  at org.monarchinitiative.vmvt.core.VmvtGenerator.getDonorDistributionSvg(VmvtGenerator.java:96)
  at 
 ... 
 (shortened)
```

Apparently, events as extreme as this one (deletion of `G` from the `GT` dinucleotide) are possible, this variant is present in the `Pfeiffer.vcf` that is shipped with Exomiser.

**Comment by pnrobinson** [comment]
The issue seems to be that this is a multinucleotide change ``TTA[gt/ta]aagt`` and both changes reduce the score.

**Comment by pnrobinson** [comment]
I think the best thing is to write a red box around the Delta Ri in these cases
![image](https://user-images.githubusercontent.com/4943420/96580095-cb05f080-12a5-11eb-8b89-71935379c7a3.png)

The bug should be fixed now. Please update to version 0.9.1 @ielis
